# Generated by Django 3.0.7 on 2020-06-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_postmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
