# Generated by Django 3.0.7 on 2020-06-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20200611_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='border',
            field=models.BooleanField(default=False, null=True, verbose_name='Доска'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
