# Generated by Django 3.0.7 on 2020-06-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_auto_20200611_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='img',
            field=models.ImageField(default='images/images.jpg', upload_to='images/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя контакта'),
        ),
    ]
