# Generated by Django 3.0.7 on 2020-06-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20200622_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='img',
            field=models.ImageField(upload_to='images/', verbose_name='Логотип'),
        ),
    ]
