# Generated by Django 3.0.7 on 2020-06-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_phonemodel_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonemodel',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email адрес'),
        ),
    ]
